{application, common_lib,
    [{description, "Common Library with some general purpose modules"},
     {vsn, "1.3"},
     {modules, [binary, 
                mnesia_seq, 
                my_calendar, 
                my_lists, 
                my_math,
                my_string,
                report,
                stats,
                xml]},
     {registered, []},
     {applications, [kernel, stdlib, xmerl]}]}.
